language: node_js
node_js:
  - 6
  - 7
  - node
cache: yarn
before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> ~/.npmrc
install: yarn install
script: yarn test
before_deploy: yarn version --message="[ci skip] bump package version" --new-version "1.$TRAVIS_BUILD_NUMBER.0"
deploy:
  provider: npm
  email: "jason@waldrip.net"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
